### ISSUE TITLE
Fix eslint security alert

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#14]
### Description
One of our dependencies, micromatch, is susceptible to a ReDoS vulnerability - https://github.com/nlp-tlp/15926-4-RDL-CITS3200/security/dependabot/1. Fix and make sure other things and dependencies that relied on this aren't broken.

**Comment by keyman015** [comment]
Issue was delayed due to update to `micromatch` dependency not being released. With its released, this issue will be resumed.
