### ISSUE TITLE
Mobile compatibility

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#42]
### Description
Test all functionality of our web interface on a phone display and fix any components that are broken.

### To-do
* [x] Test all user flows on a phone display

Add any items that need to be fixed as necessary.

**Comment by keyman015** [comment]
In reference to this issue, the bug for both side panels being open on the graph panel needs to be fixed when going down to smaller screen sizes:

![image](https://github.com/user-attachments/assets/7d88c095-9936-4bbb-8793-467dc8af8b1d)
