### ISSUE TITLE
Set up TailwindCSS for Vue

### ISSUE THREAD

**Issue by sellsol** [nlp-tlp/15926-4-RDL-CITS3200#43]
### Description
Set up Tailwind for Vue to manage styling easier. If we have the time to do so with the current priorities, rewrite the Vue files currently using `style scoped` to use Tailwind. If not then let the team know and we'll leave that for a bit later. 

### To-do
* [ ] Set up Tailwind
* [ ] *Rewrite current CSS code into Tailwind

**Comment by keyman015** [comment]
It has been determined that this issue cannot be completed within the remaining time. This issue will be closed.

**Comment by keyman015** [comment]
Branch has been re-oped due to the need to add mobile compatibility to the styling.
